//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiusDigipoort.ServiceReferenceOphalen {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class foutType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string foutcodeField;
        
        private string foutbeschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string foutcode {
            get {
                return this.foutcodeField;
            }
            set {
                this.foutcodeField = value;
                this.RaisePropertyChanged("foutcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string foutbeschrijving {
            get {
                return this.foutbeschrijvingField;
            }
            set {
                this.foutbeschrijvingField = value;
                this.RaisePropertyChanged("foutbeschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class elementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamField;
        
        private string waardeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string waarde {
            get {
                return this.waardeField;
            }
            set {
                this.waardeField = value;
                this.RaisePropertyChanged("waarde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class constateringType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string beschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string beschrijving {
            get {
                return this.beschrijvingField;
            }
            set {
                this.beschrijvingField = value;
                this.RaisePropertyChanged("beschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class berichtInhoudType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mimeTypeField;
        
        private string bestandsnaamField;
        
        private byte[] inhoudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string bestandsnaam {
            get {
                return this.bestandsnaamField;
            }
            set {
                this.bestandsnaamField = value;
                this.RaisePropertyChanged("bestandsnaam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] inhoud {
            get {
                return this.inhoudField;
            }
            set {
                this.inhoudField = value;
                this.RaisePropertyChanged("inhoud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class BerichtResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string berichtsoortField;
        
        private string berichtkenmerkField;
        
        private string aanleverkenmerkField;
        
        private string eerderAanleverkenmerkField;
        
        private System.DateTime tijdstempelAangeleverdField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string rolBelanghebbendeField;
        
        private string identiteitAanleveraarField;
        
        private identiteitType identiteitOntvangerField;
        
        private string rolOntvangerField;
        
        private berichtInhoudType berichtInhoudField;
        
        private berichtInhoudType[] berichtBijlagenField;
        
        private constateringType[] constateringenLijstField;
        
        private elementType[] additioneleElementenLijstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string berichtkenmerk {
            get {
                return this.berichtkenmerkField;
            }
            set {
                this.berichtkenmerkField = value;
                this.RaisePropertyChanged("berichtkenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string aanleverkenmerk {
            get {
                return this.aanleverkenmerkField;
            }
            set {
                this.aanleverkenmerkField = value;
                this.RaisePropertyChanged("aanleverkenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string eerderAanleverkenmerk {
            get {
                return this.eerderAanleverkenmerkField;
            }
            set {
                this.eerderAanleverkenmerkField = value;
                this.RaisePropertyChanged("eerderAanleverkenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime tijdstempelAangeleverd {
            get {
                return this.tijdstempelAangeleverdField;
            }
            set {
                this.tijdstempelAangeleverdField = value;
                this.RaisePropertyChanged("tijdstempelAangeleverd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=7)]
        public string rolBelanghebbende {
            get {
                return this.rolBelanghebbendeField;
            }
            set {
                this.rolBelanghebbendeField = value;
                this.RaisePropertyChanged("rolBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=8)]
        public string identiteitAanleveraar {
            get {
                return this.identiteitAanleveraarField;
            }
            set {
                this.identiteitAanleveraarField = value;
                this.RaisePropertyChanged("identiteitAanleveraar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public identiteitType identiteitOntvanger {
            get {
                return this.identiteitOntvangerField;
            }
            set {
                this.identiteitOntvangerField = value;
                this.RaisePropertyChanged("identiteitOntvanger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=10)]
        public string rolOntvanger {
            get {
                return this.rolOntvangerField;
            }
            set {
                this.rolOntvangerField = value;
                this.RaisePropertyChanged("rolOntvanger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public berichtInhoudType berichtInhoud {
            get {
                return this.berichtInhoudField;
            }
            set {
                this.berichtInhoudField = value;
                this.RaisePropertyChanged("berichtInhoud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bijlage", IsNullable=false)]
        public berichtInhoudType[] berichtBijlagen {
            get {
                return this.berichtBijlagenField;
            }
            set {
                this.berichtBijlagenField = value;
                this.RaisePropertyChanged("berichtBijlagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constatering", IsNullable=false)]
        public constateringType[] constateringenLijst {
            get {
                return this.constateringenLijstField;
            }
            set {
                this.constateringenLijstField = value;
                this.RaisePropertyChanged("constateringenLijst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("element", IsNullable=false)]
        public elementType[] additioneleElementenLijst {
            get {
                return this.additioneleElementenLijstField;
            }
            set {
                this.additioneleElementenLijstField = value;
                this.RaisePropertyChanged("additioneleElementenLijst");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class identiteitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nummerField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string nummer {
            get {
                return this.nummerField;
            }
            set {
                this.nummerField = value;
                this.RaisePropertyChanged("nummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/", ConfigurationName="ServiceReferenceOphalen.OphaalService_V1_2")]
    public interface OphaalService_V1_2 {
        
        // CODEGEN: Generating message contract since the operation getBerichten is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichten/F" +
            "ault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1 getBerichten(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenRe" +
            "sponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1> getBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweBerichten is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "hten/Fault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1 getNieuweBerichten(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenResponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1> getNieuweBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getBerichtenLijst is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenLijstRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenLi" +
            "jstResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenLi" +
            "jst/Fault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1 getBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenLijstRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenLi" +
            "jstResponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1> getBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweBerichtenLijst is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenLijstRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenLijstResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenLijst/Fault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1 getNieuweBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenLijstRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenLijstResponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1> getNieuweBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getBerichtenKenmerk is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenKenmerkRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenKe" +
            "nmerkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenKe" +
            "nmerk/Fault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1 getBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getBerich" +
            "tenKenmerkRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getBerichtenKe" +
            "nmerkResponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1> getBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweBerichtenKenmerk is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenKenmerkRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenKenmerkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogiusDigipoort.ServiceReferenceOphalen.foutType), Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenKenmerk/Fault/", Name="ophaalFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1 getNieuweBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService_V1_2/getNieuwe" +
            "BerichtenKenmerkRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/ophaalservice/1.2/OphaalService/getNieuweBeric" +
            "htenKenmerkResponse")]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1> getNieuweBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtResultaat[] getBerichtenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtResultaat[] getBerichtenReturn {
            get {
                return this.getBerichtenReturnField;
            }
            set {
                this.getBerichtenReturnField = value;
                this.RaisePropertyChanged("getBerichtenReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest getBerichtenRequest;
        
        public getBerichtenRequest1() {
        }
        
        public getBerichtenRequest1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest getBerichtenRequest) {
            this.getBerichtenRequest = getBerichtenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse getBerichtenResponse;
        
        public getBerichtenResponse1() {
        }
        
        public getBerichtenResponse1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse getBerichtenResponse) {
            this.getBerichtenResponse = getBerichtenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtResultaat[] getNieuweBerichtenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtResultaat[] getNieuweBerichtenReturn {
            get {
                return this.getNieuweBerichtenReturnField;
            }
            set {
                this.getNieuweBerichtenReturnField = value;
                this.RaisePropertyChanged("getNieuweBerichtenReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest getNieuweBerichtenRequest;
        
        public getNieuweBerichtenRequest1() {
        }
        
        public getNieuweBerichtenRequest1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest getNieuweBerichtenRequest) {
            this.getNieuweBerichtenRequest = getNieuweBerichtenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse getNieuweBerichtenResponse;
        
        public getNieuweBerichtenResponse1() {
        }
        
        public getNieuweBerichtenResponse1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse getNieuweBerichtenResponse) {
            this.getNieuweBerichtenResponse = getNieuweBerichtenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenLijstRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenLijstResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtLijstResultaat[] getBerichtenLijstReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtLijstResultaat[] getBerichtenLijstReturn {
            get {
                return this.getBerichtenLijstReturnField;
            }
            set {
                this.getBerichtenLijstReturnField = value;
                this.RaisePropertyChanged("getBerichtenLijstReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class BerichtLijstResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string kenmerkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenLijstRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest getBerichtenLijstRequest;
        
        public getBerichtenLijstRequest1() {
        }
        
        public getBerichtenLijstRequest1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest getBerichtenLijstRequest) {
            this.getBerichtenLijstRequest = getBerichtenLijstRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenLijstResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse getBerichtenLijstResponse;
        
        public getBerichtenLijstResponse1() {
        }
        
        public getBerichtenLijstResponse1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse getBerichtenLijstResponse) {
            this.getBerichtenLijstResponse = getBerichtenLijstResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenLijstRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenLijstResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtLijstResultaat[] getNieuweBerichtenLijstReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtLijstResultaat[] getNieuweBerichtenLijstReturn {
            get {
                return this.getNieuweBerichtenLijstReturnField;
            }
            set {
                this.getNieuweBerichtenLijstReturnField = value;
                this.RaisePropertyChanged("getNieuweBerichtenLijstReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenLijstRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest getNieuweBerichtenLijstRequest;
        
        public getNieuweBerichtenLijstRequest1() {
        }
        
        public getNieuweBerichtenLijstRequest1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest getNieuweBerichtenLijstRequest) {
            this.getNieuweBerichtenLijstRequest = getNieuweBerichtenLijstRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenLijstResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse getNieuweBerichtenLijstResponse;
        
        public getNieuweBerichtenLijstResponse1() {
        }
        
        public getNieuweBerichtenLijstResponse1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse getNieuweBerichtenLijstResponse) {
            this.getNieuweBerichtenLijstResponse = getNieuweBerichtenLijstResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenKenmerkRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtenKenmerkResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtResultaat[] getBerichtenKenmerkReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtResultaat[] getBerichtenKenmerkReturn {
            get {
                return this.getBerichtenKenmerkReturnField;
            }
            set {
                this.getBerichtenKenmerkReturnField = value;
                this.RaisePropertyChanged("getBerichtenKenmerkReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenKenmerkRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest getBerichtenKenmerkRequest;
        
        public getBerichtenKenmerkRequest1() {
        }
        
        public getBerichtenKenmerkRequest1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest getBerichtenKenmerkRequest) {
            this.getBerichtenKenmerkRequest = getBerichtenKenmerkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtenKenmerkResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse getBerichtenKenmerkResponse;
        
        public getBerichtenKenmerkResponse1() {
        }
        
        public getBerichtenKenmerkResponse1(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse getBerichtenKenmerkResponse) {
            this.getBerichtenKenmerkResponse = getBerichtenKenmerkResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenKenmerkRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweBerichtenKenmerkResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BerichtResultaat[] getNieuweBerichtenKenmerkReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BerichtResultaat[] getNieuweBerichtenKenmerkReturn {
            get {
                return this.getNieuweBerichtenKenmerkReturnField;
            }
            set {
                this.getNieuweBerichtenKenmerkReturnField = value;
                this.RaisePropertyChanged("getNieuweBerichtenKenmerkReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenKenmerkRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest getNieuweBerichtenKenmerkRequest;
        
        public getNieuweBerichtenKenmerkRequest1() {
        }
        
        public getNieuweBerichtenKenmerkRequest1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest getNieuweBerichtenKenmerkRequest) {
            this.getNieuweBerichtenKenmerkRequest = getNieuweBerichtenKenmerkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweBerichtenKenmerkResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse getNieuweBerichtenKenmerkResponse;
        
        public getNieuweBerichtenKenmerkResponse1() {
        }
        
        public getNieuweBerichtenKenmerkResponse1(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse getNieuweBerichtenKenmerkResponse) {
            this.getNieuweBerichtenKenmerkResponse = getNieuweBerichtenKenmerkResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OphaalService_V1_2Channel : LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OphaalService_V1_2Client : System.ServiceModel.ClientBase<LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2>, LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2 {
        
        public OphaalService_V1_2Client() {
        }
        
        public OphaalService_V1_2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OphaalService_V1_2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OphaalService_V1_2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OphaalService_V1_2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichten(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 request) {
            return base.Channel.getBerichten(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse getBerichten(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest getBerichtenRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1();
            inValue.getBerichtenRequest = getBerichtenRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichten(inValue);
            return retVal.getBerichtenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 request) {
            return base.Channel.getBerichtenAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenResponse1> getBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest getBerichtenRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenRequest1();
            inValue.getBerichtenRequest = getBerichtenRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichtenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichten(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 request) {
            return base.Channel.getNieuweBerichten(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse getNieuweBerichten(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest getNieuweBerichtenRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1();
            inValue.getNieuweBerichtenRequest = getNieuweBerichtenRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichten(inValue);
            return retVal.getNieuweBerichtenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 request) {
            return base.Channel.getNieuweBerichtenAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenResponse1> getNieuweBerichtenAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest getNieuweBerichtenRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenRequest1();
            inValue.getNieuweBerichtenRequest = getNieuweBerichtenRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichtenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 request) {
            return base.Channel.getBerichtenLijst(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse getBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest getBerichtenLijstRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1();
            inValue.getBerichtenLijstRequest = getBerichtenLijstRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichtenLijst(inValue);
            return retVal.getBerichtenLijstResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 request) {
            return base.Channel.getBerichtenLijstAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstResponse1> getBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest getBerichtenLijstRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenLijstRequest1();
            inValue.getBerichtenLijstRequest = getBerichtenLijstRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichtenLijstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 request) {
            return base.Channel.getNieuweBerichtenLijst(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse getNieuweBerichtenLijst(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest getNieuweBerichtenLijstRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1();
            inValue.getNieuweBerichtenLijstRequest = getNieuweBerichtenLijstRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichtenLijst(inValue);
            return retVal.getNieuweBerichtenLijstResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 request) {
            return base.Channel.getNieuweBerichtenLijstAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstResponse1> getNieuweBerichtenLijstAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest getNieuweBerichtenLijstRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenLijstRequest1();
            inValue.getNieuweBerichtenLijstRequest = getNieuweBerichtenLijstRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichtenLijstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 request) {
            return base.Channel.getBerichtenKenmerk(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse getBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest getBerichtenKenmerkRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1();
            inValue.getBerichtenKenmerkRequest = getBerichtenKenmerkRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichtenKenmerk(inValue);
            return retVal.getBerichtenKenmerkResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 request) {
            return base.Channel.getBerichtenKenmerkAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkResponse1> getBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest getBerichtenKenmerkRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getBerichtenKenmerkRequest1();
            inValue.getBerichtenKenmerkRequest = getBerichtenKenmerkRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getBerichtenKenmerkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1 LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 request) {
            return base.Channel.getNieuweBerichtenKenmerk(request);
        }
        
        public LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse getNieuweBerichtenKenmerk(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest getNieuweBerichtenKenmerkRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1();
            inValue.getNieuweBerichtenKenmerkRequest = getNieuweBerichtenKenmerkRequest;
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1 retVal = ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichtenKenmerk(inValue);
            return retVal.getNieuweBerichtenKenmerkResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1> LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2.getNieuweBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 request) {
            return base.Channel.getNieuweBerichtenKenmerkAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkResponse1> getNieuweBerichtenKenmerkAsync(LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest getNieuweBerichtenKenmerkRequest) {
            LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1 inValue = new LogiusDigipoort.ServiceReferenceOphalen.getNieuweBerichtenKenmerkRequest1();
            inValue.getNieuweBerichtenKenmerkRequest = getNieuweBerichtenKenmerkRequest;
            return ((LogiusDigipoort.ServiceReferenceOphalen.OphaalService_V1_2)(this)).getNieuweBerichtenKenmerkAsync(inValue);
        }
    }
}
